version: "2.1"
services:
  api:
    restart: always
    build: .
    environment:
      - MONGO_URI=mongodb://db:27017/goomer_rango
    ports:
      - "3000:3000"
    depends_on:
      db:
          condition: service_healthy
    networks:
     - backend
    volumes:
     - ./uploads:/usr/src/app/uploads
  db:
    image: mongo
    networks:
      - backend
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
        test:
        - CMD
        - mongo
        - --eval
        - "db.adminCommand('ping')"
networks:
    backend:
volumes: 
    db-data: